
## Code used for the analysis of the indicatorsr relevant for the Family Package.
## This file should only be runn after all other files have been run, as it uses the data generated by the other files.
# 1. Food Security Indicators
## 1.1 Livelihoods Coping Strategies Essential Needs Indicator (LCS - EN)
## 1.2 Food Isecurity Experience Scale Indicator (FIES)
## 1.3 Resilience Coping Strategies Index (rCSI)

# 2. Nutrition Indicators
## 2.1 Minimum Dietary Diversity for Women of Reproductive Age (MDD-W)
## 2.2 Minimum Acceptable Diet for Infants and Young Children (MAD) - children between 6-23 months
## 2.3 Minimum Meal Frequency for Infants and Young Children (MMF) - children between 6-23 months
## 2.4 Minimum Diet Diversity for Infants and Young Children (MDD) - children between 6-23 months
## 2.5 Concumption of Unhealthy Snacks by Children
## 2.6 Breasfeeding Practices


## Loading libraries

library(tidyverse)
library(openxlsx)
library(showtext)
library(patchwork)
library(cowplot)
library(stringr)

font_add_google("Open Sans","opensans")
showtext_auto()

source("code/SurveyDesign.R") # This file converts the data into survey designed data
source("code/Functions.R") # Functions for significance tests and creating Word documents

#calculate_proportions_and_ttest(SvyMADData, "MAD", "Treatment")

###################################################################################################################################################################

# 1 Food Security Indicators

# a. Livelihoods Coping Strategies Essential Needs Indicator (LCS - EN)

# Calculate the percentage of households using coping strategies to meet essential needs
SvyLCSENMax <- SvyLCSENData %>% 
  group_by(Treatment, MaxcopingBehaviourEN) %>% 
  summarise(Pct_LCSENMax = survey_prop() * 100) %>% 
  select( MaxcopingBehaviourEN, Treatment, Pct_LCSENMax) %>% 
  pivot_wider(names_from = Treatment, values_from = Pct_LCSENMax) %>% 
  mutate(Diff = `Treatment Group` - `Control Group`) %>% 
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>% 
  mutate(Indicator = "LCS - EN") %>%
  select(Indicator, MaxcopingBehaviourEN, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  rename(Category = MaxcopingBehaviourEN)

# Calculate the proportion of households using coping strategies to meet essential needs disgragated by regiontype
SvyLCSENMaxRegion <- SvyLCSENData %>% 
  group_by(regiontype, MaxcopingBehaviourEN) %>% 
  summarise(Pct_LCSENMax = survey_prop() * 100) %>% 
  select(regiontype, MaxcopingBehaviourEN, Pct_LCSENMax) %>% 
  rename(Proportion = Pct_LCSENMax,
         Disagregation = regiontype)

# Calculate the indicator by diability 
SvyLCSENMaxDisability <- SvyLCSENData %>% 
  group_by(DisabCategory, MaxcopingBehaviourEN) %>% 
  summarise(Pct_LCSENMax = survey_prop() * 100) %>% 
  select(DisabCategory, MaxcopingBehaviourEN, Pct_LCSENMax) %>% 
  rename(Proportion = Pct_LCSENMax,
         Disagregation = DisabCategory)

# Calculate the indicator by treatment/cpmtro
SvyLCSENMaxTreatment <- SvyLCSENData %>% 
  group_by(Treatment, MaxcopingBehaviourEN) %>% 
  summarise(Pct_LCSENMax = survey_prop() * 100) %>% 
  select(Treatment, MaxcopingBehaviourEN, Pct_LCSENMax) %>% 
  rename(Proportion = Pct_LCSENMax,
         Disagregation = Treatment)

# merge the data for hihger level disaggregation visualisations - Visualise this
HighLvlLCSEN <- bind_rows(SvyLCSENMaxRegion, SvyLCSENMaxDisability, SvyLCSENMaxTreatment)

# Calculate the proportion of the population using coping strategies to afford food
# Livelihoods Coping Strategies Food Security Indicator
# Calculate the proportion of households using coping strategies to meet food security needs
SvyLCSFSMax <- SvyLCSFS %>% 
  group_by(Treatment, MaxcopingBehaviourFS) %>% 
  summarise(Pct_LCSFSMax = survey_prop() * 100) %>% 
  select( MaxcopingBehaviourFS, Treatment, Pct_LCSFSMax) %>% 
  pivot_wider(names_from = Treatment, values_from = Pct_LCSFSMax) %>% 
  mutate(Diff = `Treatment Group` - `Control Group`) %>% 
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>% 
  mutate(Indicator = "LCS - FS") %>%
  select(Indicator, MaxcopingBehaviourFS, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  rename(Category = MaxcopingBehaviourFS)

# Merge the data
FoodSecurityCS <- bind_rows(SvyLCSENMax, SvyLCSFSMax) %>% 
  # Round all the numeric variables to 2 decimal places
  mutate_if(is.numeric, ~round(., 2))

# Write the data to an excel file
write.xlsx(FoodSecurityCS, "report tables/FoodSecurityCS.xlsx")

# Calculate the mean RCSI score

meanRCSI <- SvyrCSIData %>% 
  group_by(Treatment) %>% 
  summarise(MeanRCSI = survey_mean(rCSI)) %>% 
  select(Treatment, MeanRCSI) %>% 
  pivot_wider(names_from = Treatment, values_from = MeanRCSI) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>% 
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "rCSI") %>%
  select(Indicator, Overall, `Control Group`, `Treatment Group`, Diff)


# Calculate the same indicators disaggreagted by province - this is key for vicualisations
## Livelihoods Coping Strategies Essential Needs Indicator (LCS - EN)
SvyLCSENMaxProvince <- SvyLCSENData %>% 
  mutate(MaxcopingBehaviourFS = factor(MaxcopingBehaviourEN,
                                       levels = c("Household not adopting coping strategies",
                                                  "Stress coping strategies",
                                                  "Crisis coping strategies",
                                                  "Emergency coping strategies"))) %>%
  group_by(Province, MaxcopingBehaviourEN) %>% 
  summarise(Pct_LCSENMax = survey_prop() * 100) %>% 
  select(Province, MaxcopingBehaviourEN, Pct_LCSENMax) %>% 
  mutate(across(where(is.numeric), ~round(., 2))) %>%
  mutate(Province = if_else(Province == "Banteay Meanchey", "B. Meanchey", Province),
         Province = if_else(Province == "Kampong Cham", "K. Cham", Province),
         Province = if_else(Province == "Kampong Speu", "K. Speu", Province))

## Livelihoods Coping Strategies Essential Needs Indicator (LCS - FS)
SvyLCSENFoodProvinceTab <- SvyLCSFS %>% 
  mutate(MaxcopingBehaviourFS = factor(MaxcopingBehaviourFS,
                                       levels = c("Household not adopting coping strategies",
                                                  "Stress coping strategies",
                                                  "Crisis coping strategies",
                                                  "Emergency coping strategies"))) %>%
  group_by(Province, MaxcopingBehaviourFS) %>% 
  summarise(Pct_LCSENFood = survey_prop() * 100) %>% 
  select(Province, MaxcopingBehaviourFS, Pct_LCSENFood) %>%
  # Round all the numeric variables to 2 decimal places
  mutate_if(is.numeric, ~round(., 2)) %>% 
  mutate(Province = if_else(Province == "Banteay Meanchey", "B. Meanchey", Province))


# Save the data to an excel file
write.xlsx(SvyLCSENFoodProvinceTab, "report tables/SvyLCSENFoodProvince.xlsx")

## Reduced Coping Strategies Index (rCSI)
meanRCSIProvince <- SvyrCSIData %>% 
  group_by(Province) %>% 
  summarise(MeanRCSI = survey_mean(rCSI)) %>% 
  select(Province, MeanRCSI) #%>% 
  pivot_wider(names_from = Treatment, values_from = MeanRCSI)

###################################################################################################################################################################
# 2. Maternal Nutrition Indicators

# Calculate minimum dietary diversity for women of reproductive age (MDD-W)
MDDWomen <- SvyDietQualityData %>% 
  filter(MDDGender == "Female") %>%
  filter(MDDAge >= 15 & MDDAge <= 49) %>%
  group_by(Treatment, MDDCategory) %>% 
  summarise(MDDWomen = survey_mean() * 100) %>% 
  filter(MDDCategory == 1) %>% 
  select(-MDDWomen_se) %>% 
  pivot_wider(names_from = Treatment, values_from = MDDWomen) %>% 
  mutate(Diff = `Treatment Group` - `Control Group`) %>% 
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>% 
  mutate(Indicator = "MDD-W") %>%
  select(Indicator, MDDCategory, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  rename(Category = MDDCategory)
  
# Calculate MDD-W disagreggated by regiontype
MDDWomenRegion <- SvyDietQualityData %>% 
  filter(MDDGender == "Female") %>%
  filter(MDDAge >= 15 & MDDAge <= 49) %>%
  group_by(regiontype, MDDCategory) %>%
  summarise(MDDWomen = survey_mean() * 100) %>%
  filter(MDDCategory == 1) %>%
  select(-MDDWomen_se) %>%
  pivot_wider(names_from = regiontype, values_from = MDDWomen) %>%
  mutate(Diff = URBAN - RURAL) %>%
  mutate(Overall = (URBAN + RURAL)/2) %>%
  mutate(Indicator = "MDD-W") %>%
  select(Indicator, MDDCategory, Overall, RURAL, URBAN, Diff) %>%
  rename(Category = MDDCategory)

# # Calculate the proportion of women consuming all five food groups
# MDDWomen5Groups <- SvyDietQualityData %>% 
#   filter(MDDGender == "Female") %>%
#   filter(MDDAge >= 15 & MDDAge <= 49) %>%
#   group_by(Treatment, MDDAllGroupsCat) %>%
#   summarize(MDDWomen5Groups = survey_mean() * 100) %>% 
#   filter(MDDAllGroupsCat == "All Food groups consumed") %>%
#   select(-MDDWomen5Groups_se) %>%
#   pivot_wider(names_from = Treatment, values_from = MDDWomen5Groups) %>%
#   mutate(Diff = `Treatment Group` - `Control Group`) %>%
#   mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
#   mutate(Indicator = "MDD-W5G") %>%
#   select(Indicator, MDDAllGroupsCat, Overall, `Control Group`, `Treatment Group`, Diff) %>%
#   rename(Category = MDDAllGroupsCat)

# Calculate the Non Communicable Disease Risk Score
NCDRiskScore <- SvyDietQualityData %>%
  filter(MDDAge >= 15) %>%
  group_by(Treatment, MDDGender) %>%
  summarise(NCDRiskScore = survey_mean(NCDRiskScore),
            Total = survey_total()) %>% 
  select(-c("NCDRiskScore_se", "Total_se", "Total")) %>% 
  pivot_wider(names_from = Treatment, values_from = NCDRiskScore) %>% 
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "NCD Risk") %>% 
  select(Indicator, MDDGender, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  rename(Category = MDDGender)


NCDDRiskTot <- SvyDietQualityData %>%
  filter(MDDAge >= 15) %>%
  group_by(Treatment) %>%
  summarise(NCDRiskScore = survey_mean(NCDRiskScore),
            Total = survey_total()) %>% 
  select(-c("NCDRiskScore_se", "Total_se", "Total")) %>% 
  pivot_wider(names_from = Treatment, values_from = NCDRiskScore) %>% 
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "NCD Risk") %>% 
  select(Indicator, Overall, `Control Group`, `Treatment Group`, Diff) 

# Calculate the Non Communicable Diseases Protective Foods Score
NCDProtectiveFoods <- SvyDietQualityData %>% 
  filter(MDDAge >= 15) %>%
  group_by(Treatment, MDDGender) %>%
  summarise(NCDProtectiveFoods = survey_mean(NCDProtScore),
            Total = survey_total()) %>%
  select(-c("NCDProtectiveFoods_se", "Total_se", "Total")) %>%
  pivot_wider(names_from = Treatment, values_from = NCDProtectiveFoods) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "NCD Protective Foods") %>%
  select(Indicator, MDDGender, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  rename(Category = MDDGender)

# Calculate NCDProtectiveTot Score
NCDProtectiveTot <- SvyDietQualityData %>% 
  filter(MDDAge >= 15) %>%
  group_by(Treatment) %>%
  summarise(NCDProtectiveFoods = survey_mean(NCDProtScore),
            Total = survey_total()) %>% 
  select(-c("NCDProtectiveFoods_se", "Total_se", "Total")) %>%
  pivot_wider(names_from = Treatment, values_from = NCDProtectiveFoods) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "NCD Protective Foods") %>%
  select(Indicator, Overall, `Control Group`, `Treatment Group`, Diff)


# Calculate the GDRS Score
GDRSScore <- SvyDietQualityData %>% 
  filter(MDDAge >= 15) %>%
  group_by(Treatment, MDDGender) %>%
  summarise(GDRSScore = survey_mean(GDRScore),
            Total = survey_total()) %>% 
  select(-c("GDRSScore_se", "Total_se", "Total")) %>%
  pivot_wider(names_from = Treatment, values_from = GDRSScore) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "GDRS") %>%
  select(Indicator, MDDGender, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  rename(Category = MDDGender)

# Calculate GDRSTot Score
GDRSTot <- SvyDietQualityData %>% 
  filter(MDDAge >= 15) %>%
  group_by(Treatment) %>%
  summarise(GDRSScore = survey_mean(GDRScore),
            Total = survey_total()) %>% 
  select(-c("GDRSScore_se", "Total_se", "Total")) %>%
  pivot_wider(names_from = Treatment, values_from = GDRSScore) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "GDRS") %>%
  select(Indicator, Overall, `Control Group`, `Treatment Group`, Diff)

# Calculate MDDScore, by gender and treatment
MDDScore <- SvyDietQualityData %>% 
  filter(MDDAge >= 15) %>%
  group_by(Treatment, MDDGender) %>%
  summarise(MDDScore = survey_mean(MDDScore),
            Total = survey_total()) %>% 
  select(-c("MDDScore_se", "Total_se", "Total")) %>%
  pivot_wider(names_from = Treatment, values_from = MDDScore) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MDD Score") %>%
  select(Indicator, MDDGender, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  rename(Category = MDDGender)

# Calculate MDDScore, by treatment
MDDScoreTot <- SvyDietQualityData %>% 
  filter(MDDAge >= 15) %>%
  group_by(Treatment) %>%
  summarise(MDDScore = survey_mean(MDDScore),
            Total = survey_total()) %>% 
  select(-c("MDDScore_se", "Total_se", "Total")) %>%
  pivot_wider(names_from = Treatment, values_from = MDDScore) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MDD Score") %>%
  select(Indicator, Overall, `Control Group`, `Treatment Group`, Diff)

###Merge all the nutrition indicators####################################################
DQQNutritionIndicators <- bind_rows(MDDWomen, NCDRiskScore, NCDProtectiveFoods, GDRSScore, MDDScore) %>% 
  # Round all the numeric variables to 2 decimal places
  mutate_if(is.numeric, ~round(., 2))

#write an excel file
write.xlsx(DQQNutritionIndicators, "report tables/DQQNutritionIndicators.xlsx")




# Calculate the same indicators based on province - important for future visualisations
## Minimum Dietary Diversity for womwn of reproductive age
SvyMDDWomenRegion <- SvyDietQualityData %>% 
  filter(MDDGender == "Female") %>%
  filter(MDDAge >= 15 & MDDAge <= 49) %>%
  group_by(regiontype, MDDCategory) %>%
  summarise(MDDWomen = survey_prop() * 100,
            MDDTot = survey_total()) %>% 
  filter(MDDCategory == 1) %>%
  select(-c("MDDWomen_se", "MDDTot_se", "MDDTot", "MDDCategory"))

# ## Consumption of all five food groups by womwn of reproductive age - 5 food groups
# MDDWomen5GroupsProvince <- SvyDietQualityData %>% 
#   filter(MDDGender == "Female") %>%
#   filter(MDDAge >= 15 & MDDAge <= 49) %>%
#   group_by(Treatment, Province, MDDAllGroupsCat) %>%
#   summarize(MDDWomen5Groups = survey_mean() * 100,
#             MDDTot = survey_total()) %>% 
#   filter(MDDAllGroupsCat == "All Food groups consumed")

# Calculate the Non Communicable Disease Risk Score
NCDRiskScoreRegion <- SvyDietQualityData %>% 
  filter(MDDAge >= 15) %>%
  group_by(Treatment, regiontype) %>%
  summarise(NCDRiskScore = survey_mean(NCDRiskScore),
            Total = survey_total())

# Calcualte the Non Communicable Diseases Protective Foods Score
NCDProtectiveFoodsRegion <- SvyDietQualityData %>% 
  group_by(Treatment, regiontype) %>%
  summarise(NCDProtectiveFoods = survey_mean(NCDProtScore),
            Total = survey_total())

###########################################################################################################################

# Nutrition for children under the age of 2 years (23 months)

# Calculate the proportion of children who were breastfed over the last 24 hours
SvyMADBreasfed <- SvyMADData %>% 
  filter(ChildAgeMonths >= 0 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, PCMADBreastfeeding) %>%
  summarise(PropotionBreastfed = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("PropotionBreastfed_se", "Total_se", "Total")) %>% 
  mutate(PCMADBreastfeeding = as_factor(PCMADBreastfeeding)) %>% 
  filter(PCMADBreastfeeding == "Yes") %>% 
  pivot_wider(names_from = Treatment, values_from = PropotionBreastfed) %>% 
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "Breastfeeding") %>%
  select(Indicator, PCMADBreastfeeding, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  rename(Category = PCMADBreastfeeding) %>% 
  mutate(Category = as_factor(Category))

## Proportion of breasfed children in the last day, by child gender
SvyMADBreasfedGender <- SvyMADData %>% 
  filter(ChildAgeMonths >= 0 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, PCMADBreastfeeding, ChildGender) %>%
  summarise(PropotionBreastfed = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("PropotionBreastfed_se", "Total_se", "Total")) %>% 
  mutate(PCMADBreastfeeding = as_factor(PCMADBreastfeeding)) %>% 
  filter(PCMADBreastfeeding == "Yes") %>% 
  pivot_wider(names_from = Treatment, values_from = PropotionBreastfed) %>% 
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "Breastfeeding") %>%
  select(Indicator, PCMADBreastfeeding, ChildGender, Overall, `Control Group`, `Treatment Group`, Diff) %>% 
  mutate(ChildGender = as_factor(ChildGender))

MADBrestfedProptest <- svyttest(PCMADBreastfeeding == 1 ~ Treatment, design = SvyMADData)

# Calculate the proportion of children meeting minimum diteray diversity
SvyMDDChildren <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, MDDCat) %>%
  summarise(MDDChilden = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("MDDChilden_se", "Total_se", "Total")) %>% 
  filter(MDDCat == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = MDDChilden) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MDD") %>%
  select(Indicator, MDDCat, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = MDDCat) %>% 
  mutate(Category = as_factor(Category))

## Calculate the proportion of children meeting minimum dietary diversity, by child gender
SvyMDDChildrenGender <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, MDDCat, ChildGender) %>%
  summarise(MDDChilden = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("MDDChilden_se", "Total_se", "Total")) %>% 
  filter(MDDCat == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = MDDChilden) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MDD") %>%
  select(Indicator, MDDCat, ChildGender, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = MDDCat) %>% 
  mutate(Category = as_factor(Category),
         ChildGender = as_factor(ChildGender))

MDDChldrenProptest <- svyttest(MDDCat == 1 ~ Treatment, design = SvyMADData)

# Calculate the proportion of children who met the MMF
SvyMMFChildren <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, MMF) %>%
  summarise(MMFChildren = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("MMFChildren_se", "Total_se", "Total")) %>% 
  filter(MMF == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = MMFChildren) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MMF") %>%
  select(Indicator, MMF, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = MMF) %>% 
  mutate(Category = as_factor(Category))

## Calculate the percentage of children who met MMF, by child gender
SvyMMFChildrenGender <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, MMF, ChildGender) %>%
  summarise(MMFChildren = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("MMFChildren_se", "Total_se")) %>% 
  filter(MMF == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = MMFChildren) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MMF") %>%
  select(Indicator, MMF, ChildGender, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = MMF) %>% 
  mutate(Category = as_factor(Category),
         ChildGender = as_factor(ChildGender))

# Calculate the proportion of children who met the MMFF
SvyMMFFChildren <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  filter(!is.na(MMFF)) %>% # This code can be changed tp filter the children who are not being breastfed (Still gives the same results)
  group_by(Treatment, MMFF) %>%
  summarise(MMFFChildren = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("MMFFChildren_se", "Total_se", "Total")) %>% 
  filter(MMFF == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = MMFFChildren) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MMFF") %>%
  select(Indicator, MMFF, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = MMFF) %>% 
  mutate(Category = as_factor(Category))

## Calculate the percentage of children who met MMFF, by child gender
SvyMMFFChildrenGender <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  filter(!is.na(MMFF)) %>% # This code can be changed tp filter the children who are not being breastfed (Still gives the same results)
  group_by(Treatment, MMFF, ChildGender) %>%
  summarise(MMFFChildren = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("MMFFChildren_se", "Total_se", "Total")) %>% 
  filter(MMFF == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = MMFFChildren) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MMFF") %>%
  select(Indicator, MMFF, ChildGender, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = MMFF) %>% 
  mutate(Category = as_factor(Category),
         ChildGender = as_factor(ChildGender))


MMFProptest <- svyttest(MMF == 1 ~ ChildGender, design = SvyMADData)

# Calculate the proportion of children who met MAD
SvyMADChildren <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, MAD) %>%
  summarise(MADChildren = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("MADChildren_se", "Total_se", "Total")) %>% 
  filter(MAD == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = MADChildren) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MAD") %>%
  select(Indicator, MAD, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = MAD) %>% 
  mutate(Category = as_factor(Category))

MADProptest <- svyttest(MAD == 1 ~ Treatment, design = SvyMADData)
# MAD for children by province - for visualisation purposes - This will be useful if the sample is huge enough

SvyMADChildrenProvince <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(regiontype, MAD) %>%
  summarise(MADChildren = survey_mean() * 100,
            Total = survey_total()) %>% 
  filter(MAD == 1) %>%
  select(-MAD)


MADProptest <- svyttest(MAD == 1 ~ Treatment, design = SvyMADData)

# calculate MIXED MILK FEEDING UNDER SIX MONTHS (MixMF)
SvyMADMixMF <- SvyMADData %>% 
  filter(ChildAgeMonths >= 0 & ChildAgeMonths <= 5) %>% 
  mutate(MixMF = case_when(
    PCMADBreastfeeding == 1 & (PCMADInfFormula == 1 | PCMADMilk == 1) ~ 1,
    TRUE ~ 0)) %>%
  group_by(Treatment, MixMF) %>%
  summarise(MixMFChildren = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("MixMFChildren_se", "Total_se", "Total")) %>% 
  filter(MixMF == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = MixMFChildren) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "MixMF") %>%
  select(Indicator, MixMF, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = MixMF) %>% 
  mutate(Category = as_factor(Category))


# Calculate Sentinel Unhealthy Foods Consumption

SvyMADUnhealthyFoods <- SvyMADData %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, PCMADUnhealthyFds) %>%
  summarise(UnhealthyFoods = survey_mean() * 100,
            Total = survey_total()) %>% 
  select(-c("UnhealthyFoods_se", "Total_se", "Total")) %>% 
  filter(PCMADUnhealthyFds == 1) %>% 
  pivot_wider(names_from = Treatment, values_from = UnhealthyFoods) %>%
  mutate(Diff = `Treatment Group` - `Control Group`) %>%
  mutate(Overall = (`Control Group` + `Treatment Group`)/2) %>%
  mutate(Indicator = "UnhealthyFoods") %>%
  select(Indicator, PCMADUnhealthyFds, Overall, `Control Group`, `Treatment Group`, Diff) %>%
  rename(Category = PCMADUnhealthyFds) %>% 
  mutate(Category = as_factor(Category))


prop_test <- svyttest(PCMADUnhealthyFds == 1 ~ Treatment, design = SvyMADData)


### Merge all the child nutrition indicators
DQQChildNutritionIndicators <- bind_rows(SvyMADBreasfed, SvyMADChildren, SvyMDDChildren, SvyMMFChildren, SvyMMFFChildren, SvyMADMixMF, SvyMADUnhealthyFoods) %>% 
  # Round all the numeric variables to 2 decimal places
  mutate_if(is.numeric, ~round(., 2))

#write an excel file
write.xlsx(DQQChildNutritionIndicators, "report tables/DQQChildNutritionIndicators.xlsx")
######################################################################################################################################

## Calculate the nutrition indicators using the formula
SvyChildMDD <-  SvyMADData %>%  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>% calculate_proportions_and_ttest_nut(., "MDDCat", "Treatment")
SvyChildMMF <- calculate_proportions_and_ttest_nut(SvyMADData, "MMF", "Treatment")
SvyChildMMFF <- calculate_proportions_and_ttest_nut(SvyMADData, "MMFF", "Treatment")
SvyChildMAD <- calculate_proportions_and_ttest_nut(SvyMADData, "MAD", "Treatment")
SvyChildUnhealthyFoods <- calculate_proportions_and_ttest_nut(SvyMADData, "PCMADUnhealthyFds", "Treatment")
SvyChildBreastfeeding <- calculate_proportions_and_ttest_nut(SvyMADData, "PCMADBreastfeeding", "Treatment")
SvyChildMixMF <- calculate_proportions_and_ttest_nut(SvyMADData, "MixMF", "Treatment")

#####################################################################################################################################

# Individual components of food security indicators
# 1. FIES
FIESWorriedProvince <- FIESData %>%
  count(Province, FIESWorried) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(FIESWorried == 1) %>%
  select(Province, Pct) %>%
  rename(FIESWorried = Pct)

FIESEatHealthyProvince <- FIESData %>%
  count(Province, FIESEatHealthy) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(FIESEatHealthy == 1) %>% 
  select(Province, Pct) %>%
  rename(FIESEatHealthy = Pct)


FIESFewFoodsProvince <- FIESData %>%
  count(Province, FIESFewFoods) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(FIESFewFoods == 1) %>% 
  select(Province, Pct) %>% 
  rename(FIESFewFoods = Pct)
  

FIESSkipMealProvince <- FIESData %>%
  count(Province, FIESSkipMeal) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(FIESSkipMeal == 1) %>% 
  select(Province, Pct) %>% 
  rename(FIESSkipMeal = Pct)

FIESAteLessProvince <- FIESData %>%
  count(Province, FIESAteLess) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(FIESAteLess == 1) %>% 
  select(Province, Pct) %>%
  rename(FIESAteLess = Pct)

FIESRanOutProvince <- FIESData %>%
  count(Province, FIESRanOut) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(FIESRanOut == 1) %>%
  select(Province, Pct) %>%
  rename(FIESRanOut = Pct)

FIESHungryProvince <- FIESData %>%
  count(Province, FIESHungry) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(FIESHungry == 1) %>%
  select(Province, Pct) %>%
  rename(FIESHungry = Pct)

FIESWholeDayProvince <- FIESData %>%
  count(Province, FIESWholeDay) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(FIESWholeDay == 1) %>% 
  select(Province, Pct) %>%
  rename(FIESWholeDay = Pct)

# Join all the food security indicators together
FIESProvince <- full_join(FIESWorriedProvince, FIESEatHealthyProvince, by = "Province") %>%
  full_join(FIESFewFoodsProvince, by = "Province") %>%
  full_join(FIESSkipMealProvince, by = "Province") %>%
  full_join(FIESAteLessProvince, by = "Province") %>%
  full_join(FIESRanOutProvince, by = "Province") %>%
  full_join(FIESHungryProvince, by = "Province") %>%
  full_join(FIESWholeDayProvince, by = "Province") 


# 2. RCSI
rCSILessQltyCatProvince <- rCSIData %>% 
  count(Province, rCSILessQltyCat) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(rCSILessQltyCat == "Yes") %>%
  select(Province, Pct) %>%
  rename(rCSILessQltyCat = Pct)

rCSIBorrowCatProvince <- rCSIData %>% 
  count(Province, rCSIBorrowCat) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(rCSIBorrowCat == "Yes") %>%
  select(Province, Pct) %>%
  rename(rCSIBorrowCat = Pct)


rCSIMealSizeCatProvince <- rCSIData %>% 
  count(Province, rCSIMealSizeCat) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(rCSIMealSizeCat == "Yes") %>%
  select(Province, Pct) %>% 
  rename(rCSIMealSizeCat = Pct)

rCSIMealNbCatProvince <- rCSIData %>% 
  count(Province, rCSIMealNbCat) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(rCSIMealNbCat == "Yes") %>%
  select(Province, Pct) %>%
  rename(rCSIMealNbCat = Pct)

rCSIMealAdultCatProvince <- rCSIData %>% 
  count(Province, rCSIMealAdultCat) %>%
  group_by(Province) %>%
  mutate(Pct = n / sum(n) * 100) %>% 
  filter(rCSIMealAdultCat == "Yes") %>%
  select(Province, Pct) %>%
  rename(rCSIMealAdultCat = Pct)

# Join all the RCSI Indicators
RCSIProvince <- full_join(rCSILessQltyCatProvince, rCSIBorrowCatProvince, by = "Province") %>%
  full_join(rCSIMealSizeCatProvince, by = "Province") %>%
  full_join(rCSIMealNbCatProvince, by = "Province") %>%
  full_join(rCSIMealAdultCatProvince, by = "Province")


# rCSI without disagregating by province
rCSILessQltyCat <- rCSIData %>% 
  count(rCSILessQltyCat) %>% 
  mutate(Pct = n / sum(n) * 100) %>% 
  select(rCSILessQltyCat, Pct) %>%
  pivot_wider(names_from = rCSILessQltyCat, values_from = Pct) %>% 
  mutate(strategy = "Relied on less prefered and less expensive food",
         Percentage = Yes) %>%
  select(strategy, Percentage)

rCSIBorrowCat <- rCSIData %>%
  count(rCSIBorrowCat) %>% 
  mutate(Pct = n / sum(n) * 100) %>% 
  select(rCSIBorrowCat, Pct) %>%
  pivot_wider(names_from = rCSIBorrowCat, values_from = Pct) %>% 
  mutate(strategy = "Borrowed food from relative or friend",
         Percentage = Yes) %>%
  select(strategy, Percentage)


rCSIMealSizeCat <- rCSIData %>%
  count(rCSIMealSizeCat) %>% 
  mutate(Pct = n / sum(n) * 100) %>% 
  select(rCSIMealSizeCat, Pct) %>%
  pivot_wider(names_from = rCSIMealSizeCat, values_from = Pct) %>% 
  mutate(strategy = "Reduced meal size or portions",
         Percentage = Yes) %>%
  select(strategy, Percentage)
  

rCSIMealNbCat <- rCSIData %>%
  count(rCSIMealNbCat) %>% 
  mutate(Pct = n / sum(n) * 100) %>% 
  select(rCSIMealNbCat, Pct) %>%
  pivot_wider(names_from = rCSIMealNbCat, values_from = Pct) %>% 
  mutate(strategy = "Reduced number of meals",
         Percentage = Yes) %>%
  select(strategy, Percentage)

rCSIMealAdultCat <- rCSIData %>%
  count(rCSIMealAdultCat) %>% 
  mutate(Pct = n / sum(n) * 100) %>% 
  select(rCSIMealAdultCat, Pct) %>%
  pivot_wider(names_from = rCSIMealAdultCat, values_from = Pct) %>% 
  mutate(strategy = "Reduced meal size or portions for adults",
         Percentage = Yes) %>%
  select(strategy, Percentage)

# Bind these coping strategies together
rCSICopingStrategies <- bind_rows(rCSILessQltyCat, rCSIBorrowCat, rCSIMealSizeCat, rCSIMealNbCat, rCSIMealAdultCat) %>% 
  # Round all the numeric variables to 2 decimal places
  mutate_if(is.numeric, ~round(., 2)) %>% 
  arrange(Percentage) %>% 
  mutate(strategy = str_wrap(strategy, 20))




rCSIMealSizeWho <- rCSIData %>% 
  drop_na(rCSIMealSizeWho) %>% 
  count(rCSIMealSizeWho) %>% 
  mutate(Pct = n / sum(n) * 100) %>% 
  select(rCSIMealSizeWho, Pct) %>%
  pivot_wider(names_from = rCSIMealSizeWho, values_from = Pct) %>% 
  mutate(Indicator = "Reduced meal sizes (All HH Members)") %>% 
  select(Indicator, everything()) %>% 
  rename(`Male Adults (%)` = `Mainly adult male (18 and above)`,
         `Female Adults (%)` = `Mainly adult female (18 and above)`) %>% 
  mutate(`Other Options (%)` = `Mainly children &amp; youth male (&lt;18)` + `All adults equally` + `All family members equally`) %>%
  select(Indicator, `Male Adults (%)`, `Female Adults (%)`, `Other Options (%)`)


rCSIMealAdultWho <- rCSIData %>% 
  drop_na(rCSIMealAdultWho) %>% 
  count(rCSIMealAdultWho) %>% 
  mutate(Pct = n / sum(n) * 100) %>% 
  select(rCSIMealAdultWho, Pct) %>%
  pivot_wider(names_from = rCSIMealAdultWho, values_from = Pct) %>%
  mutate(Indicator = "Reduced meal sizes (Adults only)") %>% 
  select(Indicator, everything()) %>%
  rename(`Male Adults (%)` = `Mainly adult male (18 and above)`,
         `Female Adults (%)` = `Mainly adult female (18 and above)`,
         `Other Options (%)` = `All adults equally`) %>%
  select(Indicator, `Male Adults (%)`, `Female Adults (%)`, `Other Options (%)`)

# Merge the two tables for the visualisation
rCSIMealSizeWhoTable <- bind_rows(rCSIMealSizeWho, rCSIMealAdultWho) %>% 
  # Round all the numeric variables to 2 decimal places
  mutate_if(is.numeric, ~round(., 2))




# 3. Coping Strategies




