
## Code used for the analysis of the indicatorsr relevant for the Family Package.
## This file should only be runn after all other files have been run, as it uses the data generated by the other files.
# 1. Food Security Indicators
## 1.1 Livelihoods Coping Strategies Essential Needs Indicator (LCS - EN)
## 1.2 Food Isecurity Experience Scale Indicator (FIES)
## 1.3 Resilience Coping Strategies Index (rCSI)

# 2. Nutrition Indicators
## 2.1 Minimum Dietary Diversity for Women of Reproductive Age (MDD-W)
## 2.2 Minimum Acceptable Diet for Infants and Young Children (MAD) - children between 6-23 months
## 2.3 Minimum Meal Frequency for Infants and Young Children (MMF) - children between 6-23 months
## 2.4 Minimum Diet Diversity for Infants and Young Children (MDD) - children between 6-23 months
## 2.5 Concumption of Unhealthy Snacks by Children
## 2.6 Breasfeeding Practices


## Loading libraries

library(tidyverse)


# Source MDD.R, FoodSecurity.R and MADChildren.R, and SurveyDesign.R files Relevant files for the Baseline indicators calculation 
source("code/MDD.R")
source("code/FoodSecurity.R")
source("code/MADChildren.R")
source("code/SurveyDesign.R")

###################################################################################################################################################################

# 1 Food Security Indicators

# a. Livelihoods Coping Strategies Essential Needs Indicator (LCS - EN)

# Calculate the percentage of households using coping strategies to meet essential needs

proportions <- svyby(~Treatment, by = ~StressCopingEn, design = SvyLCSENData, FUN = svymean, na.rm = TRUE)

# b. RCSI Indicator

meanRCSI <- svyby(~rCSI, by = ~Treatment, design = SvyrCSIData, FUN = svymean, na.rm = TRUE) %>% 
  pivot_wider(names_from = Treatment, values_from = rCSI) %>% 
  select(-se) %>% 
  mutate(Indicator = "RCSI (mean)") %>% 
  select(Indicator, everything())

meanRCSI <- svyby(~rCSI, by = ~Treatment, design = SvyrCSIData, FUN = svymean, na.rm = TRUE) %>% 
  pivot_wider(names_from = Treatment, values_from = rCSI) %>% 
  select(-se) %>% 
  mutate(
    `Control Group` = coalesce(`Control Group`, `Treatment Group`),
    `Treatment Group` = coalesce(`Treatment Group`, `Control Group`)
  ) %>% 
  mutate(Indicator = "RCSI (mean)") %>% 
  select(Indicator, everything())

print(meanRCSI)



MDD <- svyby(~MDDCategory, ~Treatment, SvyDietQualityData, svymean, na.rm = TRUE)





# Calculate Relevant Indicators

# 1. Proportion of children between 6 and 23 months who have been breastfed yesterday

BreastFeeding <- MADChildren %>% 
  filter(ChildAgeMonths >= 0 & ChildAgeMonths <= 23) %>%
  group_by(Treatment, Province) %>%
  summarise(
    N = n(),
    N_Breastfed = sum(PCMADBreastfeeding == 1),
    Pct_Breastfed = N_Breastfed / N * 100,
    N_NotBreastfed = sum(PCMADBreastfeeding == 0),
    Pct_NotBreastfed = N_NotBreastfed / N * 100)


# 2. Proportion of children between 6 and 23 months who have met the MDD
MDDChildren <- MADChildren %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment) %>%
  summarise(
    N = n(),
    N_MDDMet = sum(MDDCat == 1),
    Pct_MDDMet = N_MDDMet / N * 100,
    N_MDDNotMet = sum(MDDCat == 0),
    Pct_MDDNotMet = N_MDDNotMet / N * 100)


# Calculate the proportion of children who met the MMF
MMFChildren <- MADChildren %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment) %>%
  summarise(
    N = n(),
    N_MMFMet = sum(MMF == 1),
    Pct_MMFMet = N_MMFMet / N * 100,
    N_MMFNotMet = sum(MMF == 0),
    Pct_MMFNotMet = N_MMFNotMet / N * 100)


# Calculate the proportion of children who met the MMFF
MMFFChildren <- MADChildren %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  filter(!is.na(MMFF)) %>% # This code can be changed tp filter the children who are not being breastfed (Still gives the same results)
  group_by(Treatment) %>%
  summarise(
    N = n(),
    N_MMFFMet = sum(MMFF == 1),
    Pct_MMFFMet = N_MMFFMet / N * 100,
    N_MMFFNotMet = sum(MMFF == 0),
    Pct_MMFFNotMet = N_MMFFNotMet / N * 100)

# Calculate the percentage of children who meet MAD
MADChildrenCat <- MADChildren %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment) %>%
  summarise(
    N = n(),
    N_MADMet = sum(MAD == 1),
    Pct_MADMet = N_MADMet / N * 100,
    N_MADNotMet = sum(MAD == 0),
    Pct_MADNotMet = N_MADNotMet / N * 100)


# calculate MIXED MILK FEEDING UNDER SIX MONTHS (MixMF)
MADMixMF <- MADChildren %>% 
  filter(ChildAgeMonths >= 0 & ChildAgeMonths <= 5) %>% 
  mutate(MixMF = case_when(
    PCMADBreastfeeding == 1 & (PCMADInfFormula == 1 | PCMADMilk == 1) ~ 1,
    TRUE ~ 0)) %>%
  group_by(Province, Treatment) %>%
  summarise(
    N = n(),
    N_MixMF = sum(MixMF == 1),
    Pct_MixMF = N_MixMF / N * 100,
    N_NotMixMF = sum(MixMF == 0),
    Pct_NotMixMF = N_NotMixMF / N * 100)


# Sentinel Unhealthy Foods Consumption
MADUnhealthyFoods <- MADChildren %>% 
  filter(ChildAgeMonths >= 6 & ChildAgeMonths <= 23) %>%
  group_by(Treatment) %>%
  summarise(
    N = n(),
    N_UnhealthyFoods = sum(PCMADUnhealthyFds == 1),
    Pct_UnhealthyFoods = N_UnhealthyFoods / N * 100,
    N_NoUHealthyFoods = sum(PCMADUnhealthyFds == 0),
    Pct_NoUHealthyFoods = N_NoUHealthyFoods / N * 100)









