library(tidyverse)
library(haven)
library(labelled)


## Read in the data
children_nutrition <- read_dta("data/7. UNICEF_FPBaseline_Household Roster_V11_FINAL.dta") %>% 
  # Select relevent variables
  select(interview__key, interview__id, HHRoster__id, S1A_3, S1A_4, S1A_5a,
         DOB, DOB_Day, DOB_Month, DOB_Year, DOB_Age, Age_Month, S1A_5b, S1A_5c,
         S1A_6, AGE_Mother,AGE_Father, starts_with("S6_")) %>% 
  # Convert Age_Month to numeric
  mutate(Age_Month = as.numeric(Age_Month)) %>%
  filter(Age_Month >= 0 & Age_Month <= 23) %>%
  filter(S6_1 != -5555) %>% 
  # Rename Variables
  rename(
    ChildId = HHRoster__id,
    BirthDate = DOB,
    BirthDateDay = DOB_Day,
    BirthDateMonth = DOB_Month,
    BirthDateYear = DOB_Year,
    ChildAgeMonths = Age_Month,
    ChildGender = S1A_3,
    ChildHHRelationship = S1A_4,
    ChildAgeYears = S1A_5a,
    MonthsSinceLastBD = S1A_5b,
    MotherAge = AGE_Mother,
    FatherAge = AGE_Father,
    PCMADBreastfeeding = S6_1,
    PCMADBottleLiquid = S6_2,
    PCMADPlainWAter = S6_3a,
    PCMADInfFormula = S6_3b,
    PCMADInfFormulaNum = S6_3c,
    PCMADMilk = S6_3d,
    PCMADMilkNum = S6_3e,
    PCMADMilkSwt = S6_3f,
    PCMADYogurtDrink = S6_3g,
    PCMADYogurtDrinkNum = S6_3h,
    PCMADYogurtDrinkSwt = S6_3i,
    PCMADOtherMilk = S6_3j,
    PCMADOtherMilkSwtFlavoured = S6_3l,
    PCMADChocolateFrappe = S6_3m,
    PCMADCondensedMilk = S6_3n,
    PCMADFruiteJuice = S6_3o,
    PCMADSoftDrink = S6_3p,
    PCMADTea = S6_3q,
    PCMADTeaSwt = S6_3r,
    PCMADBroth = S6_3s,
    PCMADAnyOtherLiquids = S6_3t,
    PCMADAnyOtherLiquidsSwt = S6_3u,
    PCMADYogurt = S6_4a,
    PCMADYogurtNum = S6_4a2,
    PCMADStapCereal = S6_4b,
    PCMADOtherCereal = S6_4c,
    PCMADStapTubers = S6_4d,
    PCMADStapLegumes = S6_4e,
    PCMADVegCarrots = S6_4f,
    PCMADVegIvyGourd = S6_4g,
    PCMADVegPumpkin = S6_4h,
    PCMADVegEggplant = S6_4i,
    PCMADVegWaxGourd = S6_4j,
    PCMADVegLettuce = S6_5,
    PCMADFruitRipe = S6_6,
    PCMADFruitOrange = S6_7,
    PCMADFruitBanana = S6_8,
    PCMADFruitMangosteen = S6_9,
    PCMADSweetsCakes = S6_10,
    PCMADSweetsCandy = S6_11,
    PCMADProteinEggs = S6_12,
    PCMADProteinKidney = S6_13,
    PCMADProteinSausages = S6_14,
    PCMADProteinBeef = S6_15,
    PCMADProteinPork = S6_16,
    PCMADProteinChicken = S6_17,
    PCMADProteinFish = S6_18,
    PCMADProteinCrikets = S6_19,
    PCMADOtherPeanuts = S6_20,
    PCMADOtherChips = S6_21,
    PCMADOtherNoodles = S6_22,
    PCMADOtherFriedChicken = S6_23,
    PCMADOtherSemiSolid = S6_24,
    PCMADOtherSemiSolidNm = S6_24b,
    PCMADOtherEatOut = S6_25,
    PCMADCheck = S6_26,
    PCMADNumber = S6_27) %>% 
  # Change some variables to numeric and convert to missing if the value == -5555
  mutate(
    MotherAge = ifelse(MotherAge == -5555, NA, MotherAge),
    FatherAge = ifelse(FatherAge == -5555, NA, FatherAge),
    PCMADInfFormulaNum = ifelse(PCMADInfFormulaNum == -5555, NA, PCMADInfFormulaNum),
    PCMADMilkNum = ifelse(PCMADMilkNum == -5555, NA, PCMADMilkNum),
    PCMADYogurtDrinkNum = ifelse(PCMADYogurtDrinkNum == -5555, NA, PCMADYogurtDrinkNum),
    PCMADYogurtNum = ifelse(PCMADYogurtNum == -5555, NA, PCMADYogurtNum),
    PCMADNumber = ifelse(PCMADNumber == -5555, NA, PCMADNumber)) %>%
  # Change labbeled variables to factor variables
  mutate(
    ChildGender = as_factor(ChildGender),
    ChildHHRelationship = as_factor(ChildHHRelationship),
    PCMADBreastfeeding = as_factor(PCMADBreastfeeding),
    PCMADBottleLiquid = as_factor(PCMADBottleLiquid),
    PCMADPlainWAter = as_factor(PCMADPlainWAter),
    PCMADInfFormula = as_factor(PCMADInfFormula),
    PCMADMilk = as_factor(PCMADMilk),
    PCMADMilkSwt = as_factor(PCMADMilkSwt),
    PCMADYogurtDrink = as_factor(PCMADYogurtDrink),
    PCMADYogurtDrinkSwt = as_factor(PCMADYogurtDrinkSwt),
    PCMADOtherMilk = as_factor(PCMADOtherMilk),
    PCMADOtherMilkSwtFlavoured = as_factor(PCMADOtherMilkSwtFlavoured),
    PCMADChocolateFrappe = as_factor(PCMADChocolateFrappe),
    PCMADCondensedMilk = as_factor(PCMADCondensedMilk),
    PCMADFruiteJuice = as_factor(PCMADFruiteJuice),
    PCMADSoftDrink = as_factor(PCMADSoftDrink),
    PCMADTea = as_factor(PCMADTea),
    PCMADTeaSwt = as_factor(PCMADTeaSwt),
    PCMADBroth = as_factor(PCMADBroth),
    PCMADAnyOtherLiquids = as_factor(PCMADAnyOtherLiquids),
    PCMADAnyOtherLiquidsSwt = as_factor(PCMADAnyOtherLiquidsSwt),
    PCMADYogurt = as_factor(PCMADYogurt),
    PCMADStapCereal = as_factor(PCMADStapCereal),
    PCMADOtherCereal = as_factor(PCMADOtherCereal),
    PCMADStapTubers = as_factor(PCMADStapTubers),
    PCMADStapLegumes = as_factor(PCMADStapLegumes),
    PCMADVegCarrots = as_factor(PCMADVegCarrots),
    PCMADVegIvyGourd = as_factor(PCMADVegIvyGourd),
    PCMADVegPumpkin = as_factor(PCMADVegPumpkin),
    PCMADVegEggplant = as_factor(PCMADVegEggplant),
    PCMADVegWaxGourd = as_factor(PCMADVegWaxGourd),
    PCMADVegLettuce = as_factor(PCMADVegLettuce),
    PCMADFruitRipe = as_factor(PCMADFruitRipe),
    PCMADFruitOrange = as_factor(PCMADFruitOrange),
    PCMADFruitBanana = as_factor(PCMADFruitBanana),
    PCMADFruitMangosteen = as_factor(PCMADFruitMangosteen),
    PCMADSweetsCakes = as_factor(PCMADSweetsCakes),
    PCMADSweetsCandy = as_factor(PCMADSweetsCandy),
    PCMADProteinEggs = as_factor(PCMADProteinEggs),
    PCMADProteinKidney = as_factor(PCMADProteinKidney),
    PCMADProteinSausages = as_factor(PCMADProteinSausages),
    PCMADProteinBeef = as_factor(PCMADProteinBeef),
    PCMADProteinPork = as_factor(PCMADProteinPork),
    PCMADProteinChicken = as_factor(PCMADProteinChicken),
    PCMADProteinFish = as_factor(PCMADProteinFish),
    PCMADProteinCrikets = as_factor(PCMADProteinCrikets),
    PCMADOtherPeanuts = as_factor(PCMADOtherPeanuts),
    PCMADOtherChips = as_factor(PCMADOtherChips),
    PCMADOtherNoodles = as_factor(PCMADOtherNoodles),
    PCMADOtherFriedChicken = as_factor(PCMADOtherFriedChicken),
    PCMADOtherSemiSolid = as_factor(PCMADOtherSemiSolid),
    PCMADOtherEatOut = as_factor(PCMADOtherEatOut),
    PCMADCheck = as_factor(PCMADCheck)) %>%
  # Set Variable Labels
  set_variable_labels(
    ChildId = "Child ID",
    BirthDate = "Child Birth Date",
    BirthDateDay = "Child Birth Day",
    BirthDateMonth = "Child Birth Month",
    BirthDateYear = "Child Birth Year",
    ChildAgeMonths = "Child Age (Months)",
    ChildGender = "Gender of the child",
    ChildHHRelationship = "Relationship of the child to the head of the household",
    ChildAgeYears = "Child Age (Years)",
    MonthsSinceLastBD = "Months since last birthday",
    MotherAge = "Age of the child's mother",
    FatherAge = "Age of the child's father",
    PCMADBreastfeeding = "Was the child breastfed yesterday during the day or night?",
    PCMADBottleLiquid = "Did the child drink from a bottle with a nipple yesterday during the day or night?",
    PCMADPlainWAter = "Did the child drink plain water yesterday during the day or night?",
    PCMADInfFormula = "Did the child drink infant formula (such as France Bebe, Dumex, Similax or Nutrilatt) yesterday during the day or night?",
    PCMADInfFormulaNum = "How many times did the child drink infant formularyesterday during the day or night?",
    PCMADMilk = "Did the child drink milk such tinned, powdered or fresh animal milk yesterday during the day or night?",
    PCMADMilkNum = "How many times did the child drink milk yesterday during the day or night?",
    PCMADMilkSwt = "Was the milk sweetened or flavored type of milk?",
    PCMADYogurtDrink = "Did the child drink yogurt drinks yesterday during the day or night?",
    PCMADYogurtDrinkNum = "How many times did the child drink yogurt drinks yesterday during the day or night?",
    PCMADYogurtDrinkSwt = "Was the yogurt drink sweetened or flavored?",
    PCMADOtherMilk = "Did the child drink any other type of milk (such as Soymilk, Lactasoy, or green bean milk) yesterday during the day or night?",
    PCMADOtherMilkSwtFlavoured = "Was the other type of milk sweetened or flavored?",
    PCMADChocolateFrappe = "Did the child drink chocolate frappe yesterday during the day or night?",
    PCMADCondensedMilk = "Did the child drink condensed milk yesterday during the day or night?",
    PCMADFruiteJuice = "Did the child drink fruit juice, fruit drink, sugarcane juice or fruite shake, yesterday during the day or night?",
    PCMADSoftDrink = "Did the child drink soft drinks (such as Coca Cola, Pepsi, Fanta, Sprite, Bacchus or M-150) yesterday during the day or night?",
    PCMADTea = "Did the child drink tea, coffee or herbal drinks yesterday during the day or night?",
    PCMADTeaSwt = "Was the tea sweetened?",
    PCMADBroth = "Did the child drink clear broth or clear soup yesterday during the day or night?",
    PCMADAnyOtherLiquids = "Did the child drink any other type of liquid yesterday during the day or night?",
    PCMADAnyOtherLiquidsSwt = "Was the other type of liquid sweetened?",
    PCMADYogurt = "Did the child eat yogurt other than yoghurt drinks yesterday during the day or night?",
    PCMADYogurtNum = "How many times did the child eat yogurt yesterday during the day or night?",
    PCMADStapCereal = "Did the child eat rice, khmer rice pancake, khmer noodles, glass noodles, bread, porridge or bobor krub kroeung yesterday during the day or night?",
    PCMADOtherCereal = "Did the child eat brown rice, corn or popcorn yesterday during the day or night?",
    PCMADStapTubers = "Did the child eat cassava, sweet potato, taro, cassava noodles, sweet potato, green banana, damlong daikla or potato yesterday during the day or night?",
    PCMADStapLegumes = "Did the child eat soybeans, soymilk, peas, pigeon peas, soybeans, red mung beans or mung beans, yesterday during the day or night?",
    PCMADVegCarrots = "Did the child vegetables such as carrots, pumpkin, sweet potato that are yellow or orange inside, yesterday during the day or night?",
    PCMADVegIvyGourd = "Did the child eat ivy gourd leaves, moringa leaves, green amarath, water spinach, bok choy or mustard greens, yesterday during the day or night?",
    PCMADVegPumpkin = "Did the child eat pumpkin leaves , sweat leaf bush, choy sum, spinach, kale or broccoli, yesterday during the day or night?",
    PCMADVegEggplant = "Did the child eat eggplant, cauliflower, long beans, cabbage, bean sprouts, tomatoes, or okra, or okra, yesterday during the day or night?",
    PCMADVegWaxGourd = "Did the child eat wax gourd, sponge gourd, bitter gourd, ridge gourd, bottle gourd, ivy gourd or cucumber, yesterday during the day or night?",
    PCMADVegLettuce = "Did the child eat lettuce, banana flower, mushrooms, bamboo shoots, white radish, green mango or green papaya, yesterday during the day or night?",
    PCMADFruitRipe = "Did the child eat ripe fruits such as mango, papaya, passion fruit, yesterday during the day or night?",
    PCMADFruitOrange = "Did the child eat fruits such as orange, mandarin, grapefruit or pomelo, yesterday during the day or night?",
    PCMADFruitBanana = "Did the child eat fruits such as banana, watermelon, custard apple, pineaple, jackfruit, yesterday during the day or night?",
    PCMADFruitMangosteen = "Did the child eat fruits such as mangosteen, durian, rambutan, longan or langsat, guava, dragon fruit or apple, yesterday during the day or night?",
    PCMADSweetsCakes = "Did the child eat cakes, cookies, donut, coconut sticky rice, sticky rice with coconut and egg, sticky rice with durian, sticky rice layer cake, or sweet stickyrice balls, yesterday during the day or night?",
    PCMADSweetsCandy = "Did the child eat candy, chocolate, ice cream, lot svet, mung bean pudding or coconut jellies, yesterday during the day or night?",
    PCMADProteinEggs = "Did the child eat duck or chicken eggs, yesterday during the day or night?",
    PCMADProteinKidney = "Did the child eat kidney, liver, heart, lung or blood from animal origin, yesterday during the day or night?",
    PCMADProteinSausages = "Did the child eat sausages or ham, yesterday during the day or night?",
    PCMADProteinBeef = "Did the child eat meat from beef, buffalo, lamb or goat, yesterday during the day or night?",
    PCMADProteinPork = "Did the child eat meat from pork, frog, turtle, rat, mice, or wild animal, yesterday during the day or night?",
    PCMADProteinChicken = "Did the child eat meat from chicken, duck, or goose, yesterday during the day or night?",
    PCMADProteinFish = "Did the child eat fish, seafood, eel, small shrimp, canned fish, or fermented fish, yesterday during the day or night?",
    PCMADProteinCrikets = "Did the child eat crickets, bug bacon, cockroaches, snails, spiders, termites or grasshoppers, yesterday during the day or night?",
    PCMADOtherPeanuts = "Did the child eat peanuts, sunflower seeds, watermelon seeds or pumpkin seeds, yesterday during the day or night?",
    PCMADOtherChips = "Did the child eat potato chips or shrimp chips, yesterday during the day or night?",
    PCMADOtherNoodles = "Did the child eat instant noodles, yesterday during the day or night?",
    PCMADOtherFriedChicken = "Did the child eat fried chicken, fried banana, fried sweet potato or French fries, yesterday during the day or night?",
    PCMADOtherSemiSolid = "Did the child eat any other solid, semi-solid or soft food, yesterday during the day or night?",
    PCMADOtherSemiSolidNm = "What was the other solid, semi-solid or soft food that the child ate?",
    PCMADOtherEatOut = "Did the child eat food from any place like Burger King, Pizza Company, Five Star,  restaurant, food stall, or street vendor, yesterday during the day or night?",
    PCMADCheck = "Are you sure the child did not eat any of the foods we discussed so far, yesterday during the day or night?",
    PCMADNumber = "How many times did the child eat solid, semi-solid or soft foods, yesterday during the day or night?")
  # Change labeled variables to factor variables
  
    
    
    
    
    
    
    
    
    
    
    
    
    
